/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardOperationsRouteImport } from './routes/dashboard/operations'
import { Route as DashboardInfrastructureRouteImport } from './routes/dashboard/infrastructure'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardProvisionIndexRouteImport } from './routes/dashboard/provision/index'
import { Route as DashboardSettingsUserRouteImport } from './routes/dashboard/settings/user'
import { Route as DashboardSettingsThemeRouteImport } from './routes/dashboard/settings/theme'
import { Route as DashboardSettingsOrganizationRouteImport } from './routes/dashboard/settings/organization'
import { Route as DashboardSettingsDocksRouteImport } from './routes/dashboard/settings/docks'
import { Route as DashboardProvisionProviderRouteImport } from './routes/dashboard/provision/$provider'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard/projects/$projectId'
import { Route as DashboardOperationsWorkflowsRouteImport } from './routes/dashboard/operations/workflows'
import { Route as DashboardOperationsBackupsRouteImport } from './routes/dashboard/operations/backups'
import { Route as DashboardInfrastructureNetworkingRouteImport } from './routes/dashboard/infrastructure/networking'
import { Route as DashboardInfrastructureDataRouteImport } from './routes/dashboard/infrastructure/data'
import { Route as DashboardInfrastructureComputeRouteImport } from './routes/dashboard/infrastructure/compute'
import { Route as DashboardProvisionProviderResourceTypeRouteImport } from './routes/dashboard/provision/$provider.$resourceType'
import { Route as DashboardProjectsProjectIdSettingsRouteImport } from './routes/dashboard/projects/$projectId/settings'
import { Route as DashboardProjectsProjectIdResourcesRouteImport } from './routes/dashboard/projects/$projectId/resources'
import { Route as DashboardProjectsProjectIdOverviewRouteImport } from './routes/dashboard/projects/$projectId/overview'
import { Route as DashboardProjectsProjectIdActivityRouteImport } from './routes/dashboard/projects/$projectId/activity'
import { Route as DashboardProvisionProviderResourceTypeProvisionIdRouteImport } from './routes/dashboard/provision/$provider.$resourceType.$provisionId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOperationsRoute = DashboardOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInfrastructureRoute = DashboardInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardProvisionIndexRoute = DashboardProvisionIndexRouteImport.update({
  id: '/provision/',
  path: '/provision/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsUserRoute = DashboardSettingsUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsThemeRoute = DashboardSettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsOrganizationRoute =
  DashboardSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsDocksRoute = DashboardSettingsDocksRouteImport.update({
  id: '/docks',
  path: '/docks',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardProvisionProviderRoute =
  DashboardProvisionProviderRouteImport.update({
    id: '/provision/$provider',
    path: '/provision/$provider',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardOperationsWorkflowsRoute =
  DashboardOperationsWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => DashboardOperationsRoute,
  } as any)
const DashboardOperationsBackupsRoute =
  DashboardOperationsBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => DashboardOperationsRoute,
  } as any)
const DashboardInfrastructureNetworkingRoute =
  DashboardInfrastructureNetworkingRouteImport.update({
    id: '/networking',
    path: '/networking',
    getParentRoute: () => DashboardInfrastructureRoute,
  } as any)
const DashboardInfrastructureDataRoute =
  DashboardInfrastructureDataRouteImport.update({
    id: '/data',
    path: '/data',
    getParentRoute: () => DashboardInfrastructureRoute,
  } as any)
const DashboardInfrastructureComputeRoute =
  DashboardInfrastructureComputeRouteImport.update({
    id: '/compute',
    path: '/compute',
    getParentRoute: () => DashboardInfrastructureRoute,
  } as any)
const DashboardProvisionProviderResourceTypeRoute =
  DashboardProvisionProviderResourceTypeRouteImport.update({
    id: '/$resourceType',
    path: '/$resourceType',
    getParentRoute: () => DashboardProvisionProviderRoute,
  } as any)
const DashboardProjectsProjectIdSettingsRoute =
  DashboardProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdResourcesRoute =
  DashboardProjectsProjectIdResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdOverviewRoute =
  DashboardProjectsProjectIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdActivityRoute =
  DashboardProjectsProjectIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProvisionProviderResourceTypeProvisionIdRoute =
  DashboardProvisionProviderResourceTypeProvisionIdRouteImport.update({
    id: '/$provisionId',
    path: '/$provisionId',
    getParentRoute: () => DashboardProvisionProviderResourceTypeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/infrastructure': typeof DashboardInfrastructureRouteWithChildren
  '/dashboard/operations': typeof DashboardOperationsRouteWithChildren
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/infrastructure/compute': typeof DashboardInfrastructureComputeRoute
  '/dashboard/infrastructure/data': typeof DashboardInfrastructureDataRoute
  '/dashboard/infrastructure/networking': typeof DashboardInfrastructureNetworkingRoute
  '/dashboard/operations/backups': typeof DashboardOperationsBackupsRoute
  '/dashboard/operations/workflows': typeof DashboardOperationsWorkflowsRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/provision/$provider': typeof DashboardProvisionProviderRouteWithChildren
  '/dashboard/settings/docks': typeof DashboardSettingsDocksRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/theme': typeof DashboardSettingsThemeRoute
  '/dashboard/settings/user': typeof DashboardSettingsUserRoute
  '/dashboard/provision': typeof DashboardProvisionIndexRoute
  '/dashboard/projects/$projectId/activity': typeof DashboardProjectsProjectIdActivityRoute
  '/dashboard/projects/$projectId/overview': typeof DashboardProjectsProjectIdOverviewRoute
  '/dashboard/projects/$projectId/resources': typeof DashboardProjectsProjectIdResourcesRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/provision/$provider/$resourceType': typeof DashboardProvisionProviderResourceTypeRouteWithChildren
  '/dashboard/provision/$provider/$resourceType/$provisionId': typeof DashboardProvisionProviderResourceTypeProvisionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/infrastructure': typeof DashboardInfrastructureRouteWithChildren
  '/dashboard/operations': typeof DashboardOperationsRouteWithChildren
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/infrastructure/compute': typeof DashboardInfrastructureComputeRoute
  '/dashboard/infrastructure/data': typeof DashboardInfrastructureDataRoute
  '/dashboard/infrastructure/networking': typeof DashboardInfrastructureNetworkingRoute
  '/dashboard/operations/backups': typeof DashboardOperationsBackupsRoute
  '/dashboard/operations/workflows': typeof DashboardOperationsWorkflowsRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/provision/$provider': typeof DashboardProvisionProviderRouteWithChildren
  '/dashboard/settings/docks': typeof DashboardSettingsDocksRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/theme': typeof DashboardSettingsThemeRoute
  '/dashboard/settings/user': typeof DashboardSettingsUserRoute
  '/dashboard/provision': typeof DashboardProvisionIndexRoute
  '/dashboard/projects/$projectId/activity': typeof DashboardProjectsProjectIdActivityRoute
  '/dashboard/projects/$projectId/overview': typeof DashboardProjectsProjectIdOverviewRoute
  '/dashboard/projects/$projectId/resources': typeof DashboardProjectsProjectIdResourcesRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/provision/$provider/$resourceType': typeof DashboardProvisionProviderResourceTypeRouteWithChildren
  '/dashboard/provision/$provider/$resourceType/$provisionId': typeof DashboardProvisionProviderResourceTypeProvisionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/infrastructure': typeof DashboardInfrastructureRouteWithChildren
  '/dashboard/operations': typeof DashboardOperationsRouteWithChildren
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/infrastructure/compute': typeof DashboardInfrastructureComputeRoute
  '/dashboard/infrastructure/data': typeof DashboardInfrastructureDataRoute
  '/dashboard/infrastructure/networking': typeof DashboardInfrastructureNetworkingRoute
  '/dashboard/operations/backups': typeof DashboardOperationsBackupsRoute
  '/dashboard/operations/workflows': typeof DashboardOperationsWorkflowsRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/provision/$provider': typeof DashboardProvisionProviderRouteWithChildren
  '/dashboard/settings/docks': typeof DashboardSettingsDocksRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/theme': typeof DashboardSettingsThemeRoute
  '/dashboard/settings/user': typeof DashboardSettingsUserRoute
  '/dashboard/provision/': typeof DashboardProvisionIndexRoute
  '/dashboard/projects/$projectId/activity': typeof DashboardProjectsProjectIdActivityRoute
  '/dashboard/projects/$projectId/overview': typeof DashboardProjectsProjectIdOverviewRoute
  '/dashboard/projects/$projectId/resources': typeof DashboardProjectsProjectIdResourcesRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/provision/$provider/$resourceType': typeof DashboardProvisionProviderResourceTypeRouteWithChildren
  '/dashboard/provision/$provider/$resourceType/$provisionId': typeof DashboardProvisionProviderResourceTypeProvisionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/infrastructure'
    | '/dashboard/operations'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/infrastructure/compute'
    | '/dashboard/infrastructure/data'
    | '/dashboard/infrastructure/networking'
    | '/dashboard/operations/backups'
    | '/dashboard/operations/workflows'
    | '/dashboard/projects/$projectId'
    | '/dashboard/provision/$provider'
    | '/dashboard/settings/docks'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/theme'
    | '/dashboard/settings/user'
    | '/dashboard/provision'
    | '/dashboard/projects/$projectId/activity'
    | '/dashboard/projects/$projectId/overview'
    | '/dashboard/projects/$projectId/resources'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/provision/$provider/$resourceType'
    | '/dashboard/provision/$provider/$resourceType/$provisionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/infrastructure'
    | '/dashboard/operations'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/infrastructure/compute'
    | '/dashboard/infrastructure/data'
    | '/dashboard/infrastructure/networking'
    | '/dashboard/operations/backups'
    | '/dashboard/operations/workflows'
    | '/dashboard/projects/$projectId'
    | '/dashboard/provision/$provider'
    | '/dashboard/settings/docks'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/theme'
    | '/dashboard/settings/user'
    | '/dashboard/provision'
    | '/dashboard/projects/$projectId/activity'
    | '/dashboard/projects/$projectId/overview'
    | '/dashboard/projects/$projectId/resources'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/provision/$provider/$resourceType'
    | '/dashboard/provision/$provider/$resourceType/$provisionId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/infrastructure'
    | '/dashboard/operations'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/infrastructure/compute'
    | '/dashboard/infrastructure/data'
    | '/dashboard/infrastructure/networking'
    | '/dashboard/operations/backups'
    | '/dashboard/operations/workflows'
    | '/dashboard/projects/$projectId'
    | '/dashboard/provision/$provider'
    | '/dashboard/settings/docks'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/theme'
    | '/dashboard/settings/user'
    | '/dashboard/provision/'
    | '/dashboard/projects/$projectId/activity'
    | '/dashboard/projects/$projectId/overview'
    | '/dashboard/projects/$projectId/resources'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/provision/$provider/$resourceType'
    | '/dashboard/provision/$provider/$resourceType/$provisionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/operations': {
      id: '/dashboard/operations'
      path: '/operations'
      fullPath: '/dashboard/operations'
      preLoaderRoute: typeof DashboardOperationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/infrastructure': {
      id: '/dashboard/infrastructure'
      path: '/infrastructure'
      fullPath: '/dashboard/infrastructure'
      preLoaderRoute: typeof DashboardInfrastructureRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/provision/': {
      id: '/dashboard/provision/'
      path: '/provision'
      fullPath: '/dashboard/provision'
      preLoaderRoute: typeof DashboardProvisionIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/user': {
      id: '/dashboard/settings/user'
      path: '/user'
      fullPath: '/dashboard/settings/user'
      preLoaderRoute: typeof DashboardSettingsUserRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/theme': {
      id: '/dashboard/settings/theme'
      path: '/theme'
      fullPath: '/dashboard/settings/theme'
      preLoaderRoute: typeof DashboardSettingsThemeRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/organization': {
      id: '/dashboard/settings/organization'
      path: '/organization'
      fullPath: '/dashboard/settings/organization'
      preLoaderRoute: typeof DashboardSettingsOrganizationRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/docks': {
      id: '/dashboard/settings/docks'
      path: '/docks'
      fullPath: '/dashboard/settings/docks'
      preLoaderRoute: typeof DashboardSettingsDocksRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/provision/$provider': {
      id: '/dashboard/provision/$provider'
      path: '/provision/$provider'
      fullPath: '/dashboard/provision/$provider'
      preLoaderRoute: typeof DashboardProvisionProviderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/dashboard/operations/workflows': {
      id: '/dashboard/operations/workflows'
      path: '/workflows'
      fullPath: '/dashboard/operations/workflows'
      preLoaderRoute: typeof DashboardOperationsWorkflowsRouteImport
      parentRoute: typeof DashboardOperationsRoute
    }
    '/dashboard/operations/backups': {
      id: '/dashboard/operations/backups'
      path: '/backups'
      fullPath: '/dashboard/operations/backups'
      preLoaderRoute: typeof DashboardOperationsBackupsRouteImport
      parentRoute: typeof DashboardOperationsRoute
    }
    '/dashboard/infrastructure/networking': {
      id: '/dashboard/infrastructure/networking'
      path: '/networking'
      fullPath: '/dashboard/infrastructure/networking'
      preLoaderRoute: typeof DashboardInfrastructureNetworkingRouteImport
      parentRoute: typeof DashboardInfrastructureRoute
    }
    '/dashboard/infrastructure/data': {
      id: '/dashboard/infrastructure/data'
      path: '/data'
      fullPath: '/dashboard/infrastructure/data'
      preLoaderRoute: typeof DashboardInfrastructureDataRouteImport
      parentRoute: typeof DashboardInfrastructureRoute
    }
    '/dashboard/infrastructure/compute': {
      id: '/dashboard/infrastructure/compute'
      path: '/compute'
      fullPath: '/dashboard/infrastructure/compute'
      preLoaderRoute: typeof DashboardInfrastructureComputeRouteImport
      parentRoute: typeof DashboardInfrastructureRoute
    }
    '/dashboard/provision/$provider/$resourceType': {
      id: '/dashboard/provision/$provider/$resourceType'
      path: '/$resourceType'
      fullPath: '/dashboard/provision/$provider/$resourceType'
      preLoaderRoute: typeof DashboardProvisionProviderResourceTypeRouteImport
      parentRoute: typeof DashboardProvisionProviderRoute
    }
    '/dashboard/projects/$projectId/settings': {
      id: '/dashboard/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/dashboard/projects/$projectId/settings'
      preLoaderRoute: typeof DashboardProjectsProjectIdSettingsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/resources': {
      id: '/dashboard/projects/$projectId/resources'
      path: '/resources'
      fullPath: '/dashboard/projects/$projectId/resources'
      preLoaderRoute: typeof DashboardProjectsProjectIdResourcesRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/overview': {
      id: '/dashboard/projects/$projectId/overview'
      path: '/overview'
      fullPath: '/dashboard/projects/$projectId/overview'
      preLoaderRoute: typeof DashboardProjectsProjectIdOverviewRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/activity': {
      id: '/dashboard/projects/$projectId/activity'
      path: '/activity'
      fullPath: '/dashboard/projects/$projectId/activity'
      preLoaderRoute: typeof DashboardProjectsProjectIdActivityRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/provision/$provider/$resourceType/$provisionId': {
      id: '/dashboard/provision/$provider/$resourceType/$provisionId'
      path: '/$provisionId'
      fullPath: '/dashboard/provision/$provider/$resourceType/$provisionId'
      preLoaderRoute: typeof DashboardProvisionProviderResourceTypeProvisionIdRouteImport
      parentRoute: typeof DashboardProvisionProviderResourceTypeRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardInfrastructureRouteChildren {
  DashboardInfrastructureComputeRoute: typeof DashboardInfrastructureComputeRoute
  DashboardInfrastructureDataRoute: typeof DashboardInfrastructureDataRoute
  DashboardInfrastructureNetworkingRoute: typeof DashboardInfrastructureNetworkingRoute
}

const DashboardInfrastructureRouteChildren: DashboardInfrastructureRouteChildren =
  {
    DashboardInfrastructureComputeRoute: DashboardInfrastructureComputeRoute,
    DashboardInfrastructureDataRoute: DashboardInfrastructureDataRoute,
    DashboardInfrastructureNetworkingRoute:
      DashboardInfrastructureNetworkingRoute,
  }

const DashboardInfrastructureRouteWithChildren =
  DashboardInfrastructureRoute._addFileChildren(
    DashboardInfrastructureRouteChildren,
  )

interface DashboardOperationsRouteChildren {
  DashboardOperationsBackupsRoute: typeof DashboardOperationsBackupsRoute
  DashboardOperationsWorkflowsRoute: typeof DashboardOperationsWorkflowsRoute
}

const DashboardOperationsRouteChildren: DashboardOperationsRouteChildren = {
  DashboardOperationsBackupsRoute: DashboardOperationsBackupsRoute,
  DashboardOperationsWorkflowsRoute: DashboardOperationsWorkflowsRoute,
}

const DashboardOperationsRouteWithChildren =
  DashboardOperationsRoute._addFileChildren(DashboardOperationsRouteChildren)

interface DashboardProjectsProjectIdRouteChildren {
  DashboardProjectsProjectIdActivityRoute: typeof DashboardProjectsProjectIdActivityRoute
  DashboardProjectsProjectIdOverviewRoute: typeof DashboardProjectsProjectIdOverviewRoute
  DashboardProjectsProjectIdResourcesRoute: typeof DashboardProjectsProjectIdResourcesRoute
  DashboardProjectsProjectIdSettingsRoute: typeof DashboardProjectsProjectIdSettingsRoute
}

const DashboardProjectsProjectIdRouteChildren: DashboardProjectsProjectIdRouteChildren =
  {
    DashboardProjectsProjectIdActivityRoute:
      DashboardProjectsProjectIdActivityRoute,
    DashboardProjectsProjectIdOverviewRoute:
      DashboardProjectsProjectIdOverviewRoute,
    DashboardProjectsProjectIdResourcesRoute:
      DashboardProjectsProjectIdResourcesRoute,
    DashboardProjectsProjectIdSettingsRoute:
      DashboardProjectsProjectIdSettingsRoute,
  }

const DashboardProjectsProjectIdRouteWithChildren =
  DashboardProjectsProjectIdRoute._addFileChildren(
    DashboardProjectsProjectIdRouteChildren,
  )

interface DashboardProjectsRouteChildren {
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRouteWithChildren
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRouteWithChildren,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardSettingsRouteChildren {
  DashboardSettingsDocksRoute: typeof DashboardSettingsDocksRoute
  DashboardSettingsOrganizationRoute: typeof DashboardSettingsOrganizationRoute
  DashboardSettingsThemeRoute: typeof DashboardSettingsThemeRoute
  DashboardSettingsUserRoute: typeof DashboardSettingsUserRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsDocksRoute: DashboardSettingsDocksRoute,
  DashboardSettingsOrganizationRoute: DashboardSettingsOrganizationRoute,
  DashboardSettingsThemeRoute: DashboardSettingsThemeRoute,
  DashboardSettingsUserRoute: DashboardSettingsUserRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardProvisionProviderResourceTypeRouteChildren {
  DashboardProvisionProviderResourceTypeProvisionIdRoute: typeof DashboardProvisionProviderResourceTypeProvisionIdRoute
}

const DashboardProvisionProviderResourceTypeRouteChildren: DashboardProvisionProviderResourceTypeRouteChildren =
  {
    DashboardProvisionProviderResourceTypeProvisionIdRoute:
      DashboardProvisionProviderResourceTypeProvisionIdRoute,
  }

const DashboardProvisionProviderResourceTypeRouteWithChildren =
  DashboardProvisionProviderResourceTypeRoute._addFileChildren(
    DashboardProvisionProviderResourceTypeRouteChildren,
  )

interface DashboardProvisionProviderRouteChildren {
  DashboardProvisionProviderResourceTypeRoute: typeof DashboardProvisionProviderResourceTypeRouteWithChildren
}

const DashboardProvisionProviderRouteChildren: DashboardProvisionProviderRouteChildren =
  {
    DashboardProvisionProviderResourceTypeRoute:
      DashboardProvisionProviderResourceTypeRouteWithChildren,
  }

const DashboardProvisionProviderRouteWithChildren =
  DashboardProvisionProviderRoute._addFileChildren(
    DashboardProvisionProviderRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardInfrastructureRoute: typeof DashboardInfrastructureRouteWithChildren
  DashboardOperationsRoute: typeof DashboardOperationsRouteWithChildren
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProvisionProviderRoute: typeof DashboardProvisionProviderRouteWithChildren
  DashboardProvisionIndexRoute: typeof DashboardProvisionIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardInfrastructureRoute: DashboardInfrastructureRouteWithChildren,
  DashboardOperationsRoute: DashboardOperationsRouteWithChildren,
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProvisionProviderRoute: DashboardProvisionProviderRouteWithChildren,
  DashboardProvisionIndexRoute: DashboardProvisionIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
