"""Session-based multi-user auth.

- Passwords hashed with bcrypt.
- Sessions are signed cookies (itsdangerous), 30-day lifetime, HttpOnly.
- Signup requires a one-time invite code generated by an admin.
- Password resets use one-time links (1 h expiry) generated by an admin —
  no email infrastructure needed for a four-person app.
"""
import hashlib
import secrets
from datetime import datetime, timedelta, timezone
from urllib.parse import quote

import bcrypt
from fastapi import HTTPException, Request
from itsdangerous import BadSignature, URLSafeTimedSerializer

from . import config, db

# Verified against when a login names a nonexistent user, so the response takes
# one bcrypt check either way (no username enumeration via timing).
_DUMMY_HASH = bcrypt.hashpw(b"stackdock-timing-pad", bcrypt.gensalt()).decode()

SESSION_COOKIE = "stackdock_session"
SESSION_MAX_AGE = 30 * 24 * 3600  # 30 days
RESET_TTL_HOURS = 1

_serializer = URLSafeTimedSerializer(config.SECRET_KEY, salt="stackdock-session")


# ---------- passwords ----------

def hash_password(password: str) -> str:
    return bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()


def verify_password(password: str, password_hash: str) -> bool:
    try:
        return bcrypt.checkpw(password.encode(), password_hash.encode())
    except ValueError:
        return False


def check_login(user, password: str) -> bool:
    """verify_password with a constant-time shape: unknown usernames still pay
    one bcrypt check so response timing doesn't reveal which usernames exist."""
    if user is None:
        verify_password(password, _DUMMY_HASH)
        return False
    return verify_password(password, user["password_hash"])


# ---------- sessions ----------

def make_session_value(user_id: int) -> str:
    return _serializer.dumps({"uid": user_id})


def read_session_value(value: str):
    try:
        data = _serializer.loads(value, max_age=SESSION_MAX_AGE)
        return data.get("uid")
    except BadSignature:
        return None


def set_session_cookie(response, user_id: int) -> None:
    response.set_cookie(
        SESSION_COOKIE,
        make_session_value(user_id),
        max_age=SESSION_MAX_AGE,
        httponly=True,
        secure=config.PUBLIC_BASE_URL.startswith("https"),
        samesite="lax",
    )


def clear_session_cookie(response) -> None:
    response.delete_cookie(SESSION_COOKIE)


# ---------- FastAPI dependencies ----------

def _redirect_to_login(request: Request):
    # API/beacon clients must get a real error, not a 303: fetch() follows the
    # redirect to /login and reports a misleading 200, so an expired session
    # would silently "succeed" (and the offline saver would cache the login
    # page as audio).
    if request.url.path.startswith("/api/"):
        raise HTTPException(status_code=401, detail="Session expired")
    target = request.url.path + (f"?{request.url.query}" if request.url.query else "")
    raise HTTPException(
        status_code=303,
        headers={"Location": f"/login?next={quote(target, safe='/?&=')}"},
    )


def current_user(request: Request):
    """Require a logged-in user; redirects browsers to /login."""
    value = request.cookies.get(SESSION_COOKIE)
    uid = read_session_value(value) if value else None
    user = db.get_user(uid) if uid else None
    if not user:
        _redirect_to_login(request)
    return user


def current_admin(request: Request):
    user = current_user(request)
    if not user["is_admin"]:
        raise HTTPException(status_code=403, detail="Admin only")
    return user


# ---------- bootstrap, invites, resets ----------

def ensure_admin_user() -> None:
    """On first run, seed the admin account from BASIC_AUTH_USER/PASS env vars."""
    if db.user_count() == 0:
        db.create_user(
            config.BASIC_AUTH_USER,
            hash_password(config.BASIC_AUTH_PASS),
            is_admin=True,
        )


def new_invite_code() -> str:
    code = secrets.token_urlsafe(12)
    db.create_invite(code)
    return code


def _hash_token(token: str) -> str:
    return hashlib.sha256(token.encode()).hexdigest()


def new_reset_link(user_id: int) -> str:
    token = secrets.token_urlsafe(32)
    expires = (datetime.now(timezone.utc) + timedelta(hours=RESET_TTL_HOURS)).isoformat()
    db.create_reset_token(_hash_token(token), user_id, expires)
    return f"{config.PUBLIC_BASE_URL}/reset/{token}"


def redeem_reset_token(token: str):
    """Return user_id if the token is valid (and burn it), else None."""
    return db.consume_reset_token(_hash_token(token))
