import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const outfit = localFont({
  src: [
    {
      path: './fonts/Outfit-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Outfit-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-outfit',
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${outfit.variable} ${outfit.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
